### PR TITLE
Perf json fix uncore events using filter1

### PR DESCRIPTION
**Pull request by weilinwa**
This update has changes to fix the uncore event not supported bug reported here: [lkml bug link](https://lore.kernel.org/lkml/CAPhsuW4nem9XZP+b=sJJ7kqXG-cafz0djZf51HsgjCiwkGBA+A@mail.gmail.com/).

### CODE REVIEW

**Comment by edwarddavidbaker** [comment]
Can you also add submit script updates? I expected this to modify lines such as  https://github.com/intel/perfmon/blob/main/scripts/create_perf_json.py#L394 or https://github.com/intel/perfmon/blob/main/scripts/create_perf_json.py#L1728 .

**Comment by weilinwa** [comment]
> Can you also add submit script updates? I expected this to modify lines such as https://github.com/intel/perfmon/blob/main/scripts/create_perf_json.py#L394 or https://github.com/intel/perfmon/blob/main/scripts/create_perf_json.py#L1728 .

Hi @edwarddavidbaker, these changes are on top of changes I added for TMA4.8 and E-core 3.6 release. Do you want me to push all the changes or only have the updates for this specific fix?

BTW, I'm going to upload another set of changes of the script that would remove dependency on the spreadsheet. I'm wondering if we want to work with PR directly to the main branch or create a different branch for it. Do you have any suggestions?

**Comment by edwarddavidbaker** [comment]
> Hi @edwarddavidbaker, these changes are on top of changes I added for TMA4.8 and E-core 3.6 release. Do you want me to push all the changes or only have the updates for this specific fix?

In that case please submit them with the rest of the script updates in a separate PR.

> BTW, I'm going to upload another set of changes of the script that would remove dependency on the spreadsheet. I'm wondering if we want to work with PR directly to the main branch or create a different branch for it. Do you have any suggestions?

All pull requests should target the main branch.

**Review by edwarddavidbaker — APPROVED** [review]
LGTM. Please submit script changes in a follow-up pull request.

**Review by captain5050 — APPROVED** [review]

**Pull request merged**
