### PR TITLE
EMR, SPR, ARL, LNL, HSX, HSW, BDX, BDW, BDW-DE: Release event updates

### PR DESCRIPTION
**Pull request by edwarddavidbaker**
* ARL
  * Release a comprehensive set of P-Core, E-Core, and uncore events.
* LNL
  * Add numerous E-Core events.
  * Release P-Core `MEM_STORE_RETIRED.MEMSIDE_CACHE`, `MEM_LOAD_L3_MISS_RETIRED.MEMSIDE_CACHE`, and update `UOPS_DISPATCHED.*` descriptions.
* EMR, SPR
  * Update `RTM_RETIRED.ABORTED_EVENTS` description and move `UNC_IIO_DATA_REQ_OF_CPU.MEM_[READ, WRITE].ALL_PARTS`  out of experimental.
* HSX
  * Fix event JSON attributes. Remove uncore event file attributes `MSRValue` and `EVENT_STATUS`. Add `Deprecated`.
  * Fix spelling issues `startved`, `filted`, `banwidth`, `servied`, `occpancy`, and `Trackes`.
* HSW
  * Update `PEBS` value for `RTM_RETIRED.ABORTED`.
* BDX, BDW-DE
  * Remove encoded newlines in descriptions.
  * Fix event JSON attributes. Remove uncore event file attribute `MSRValue` and add `Deprecated`.
  * Fix spelling issues `banwidth`, `filted`, `occpancy`, `servied`, and `startved`.
* BDW
  *  Remove encoded newlines in descriptions.

### CODE REVIEW

**Comment by edwarddavidbaker** [comment]
@captain5050, @weilinwa : Let me know if you see anything unexpected with the `create_perf_json.py` changes. One adds ARL to the set of platforms that needs to handle `imc_free_running` types. The other adds both LNL and ARL to list of platforms to skip when writing `counter.json`.

**Comment by captain5050** [comment]
Thanks Ed, I didn't have any comments. We're in a bit of a funny state with the converter script as the Linux kernel perf json uses TMA 4.8, the converter script is using the TMA 4.7 spreadsheet in the repo and Weilin and I have private modifications to the converter script to get everything working.. hopefully this will be rectified soon with the full switch to Valkyrie metrics.

**Comment by edwarddavidbaker** [comment]
> Thanks Ed, I didn't have any comments. We're in a bit of a funny state with the converter script as the Linux kernel perf json uses TMA 4.8, the converter script is using the TMA 4.7 spreadsheet in the repo and Weilin and I have private modifications to the converter script to get everything working.. hopefully this will be rectified soon with the full switch to Valkyrie metrics.

Thanks for the details Ian. I appreciate your help.

**Comment by weilinwa** [comment]
> Thanks Ed, I didn't have any comments. We're in a bit of a funny state with the converter script as the Linux kernel perf json uses TMA 4.8, the converter script is using the TMA 4.7 spreadsheet in the repo and Weilin and I have private modifications to the converter script to get everything working.. hopefully this will be rectified soon with the full switch to Valkyrie metrics.

@captain5050, I have an initial version of the script that uses Valkyrie metric input only now. We are working on finalizing this first version. We should be able to upload it for reviewing soon.

**Comment by captain5050** [comment]
> > Thanks Ed, I didn't have any comments. We're in a bit of a funny state with the converter script as the Linux kernel perf json uses TMA 4.8, the converter script is using the TMA 4.7 spreadsheet in the repo and Weilin and I have private modifications to the converter script to get everything working.. hopefully this will be rectified soon with the full switch to Valkyrie metrics.
> 
> @captain5050, I have an initial version of the script that uses Valkyrie metric input only now. We are working on finalizing this first version. We should be able to upload it for reviewing soon.

That's great! I'm asking the perf tool maintainers to land the reviewed TPEBS changes. Somehow the perf-tools-next tree has managed to become quite out of date with the preparation tree tmp.perf-tools-next. People are looking at the problem so hopefully progress soon.

**Pull request merged**
