### PR TITLE
Introduce JSON Header

### PR DESCRIPTION
**Pull request by edwarddavidbaker**
This pull request updates all event files with the new JSON structure documented in https://github.com/intel/perfmon/issues/22 . No other modifications to event files are made. Since indentation is changing, the best way to view this pull request is to diff ignoring whitespace. Closes https://github.com/intel/perfmon/issues/22 .
```
git diff -w main json-header
```
All changes should be the same general form as the example below.
```
diff --git a/ADL/events/alderlake_goldencove_core.json b/ADL/events/alderlake_goldencove_core.json
index 9c61818..b05b059 100644
--- a/ADL/events/alderlake_goldencove_core.json
+++ b/ADL/events/alderlake_goldencove_core.json
@@ -1,4 +1,12 @@
-[
+{
+  "Header": {
+    "Copyright": "Copyright (c) 2001 - 2022 Intel Corporation. All rights reserved.",
+    "Info": "Performance Monitoring Events for 12th and 13th Generation Intel(R) Core(TM) Processor - V1.16",
+    "DatePublished": "10/18/2022",
+    "Version": "1.16",
+    "Legend": ""
+  },
+  "Events": [
     {
       "EventCode": "0x00",
       "UMask": "0x01",
@@ -6792,3 +6800,4 @@
       "Speculative": "1"
     }
   ]
+}
```

### CODE REVIEW

**Comment by rpmclaug** [comment]
Looks good. Passed intermediate format checks.

**Review by kshiprab — COMMENTED** [review]
Ryan/Ed json schema changes check is there any report generated ?  Who runs the check ?

**Comment by rpmclaug** [comment]
@kshiprab Schemas are still under discussion. At present they are only checked manually, and only when we suspect we may have impacted the format (such as this change). There isn't a formal owner of running this at a set interval but I'm more or less responsible for the manual checks if we have reason to suspect format impact (tool changes, introduction of this header, etc). 

Ed and I have discussed a rough path to how we could get good basic/intermediate schema validation as part of automation, but first have some tasks (See known issues noted in Jira) and discussions before we can establish clear cut schemas.

**Comment by edwarddavidbaker** [comment]
@captain5050 I quickly checked your inflight scripts by merging your pull request into two branches. One off of main, and one off of this JSON structure change. To pull events from the new structure I temporarily tweaked your script.
```
-                pmon_events: list[PerfmonJsonEvent] = \
-                    json.load(event_json, object_hook=PerfmonJsonEvent)
+                json_data = json.load(event_json)
+                pmon_events = [PerfmonJsonEvent(x) for x in json_data['Events']]
```

I then ran the command from each branch and diffed the output.
```
$ python3 create_perf_json.py --outdir out-main --verbose
<switch branch>
$ python3 create_perf_json.py --outdir out-json-headers --verbose
```

The few changes are slight version modifications to the output mapfile.csv. For each of these platforms the specific commit also mentions the version change.
```
$ diff -rup out-main/ out-json-headers/
diff -rup out-main/mapfile.csv out-json-headers/mapfile.csv
--- out-main/mapfile.csv        2022-11-17 15:21:13.920000000 -0700
+++ out-json-headers/mapfile.csv        2022-11-17 15:20:38.010000000 -0700
@@ -1,7 +1,7 @@
 GenuineIntel-6-(97|9A|B7|BA|BE|BF),v1.16,alderlake,core
 GenuineIntel-6-(1C|26|27|35|36),v4,bonnell,core
 GenuineIntel-6-(3D|47),v26,broadwell,core
-GenuineIntel-6-56,v23,broadwellde,core
+GenuineIntel-6-56,v7,broadwellde,core
 GenuineIntel-6-4F,v19,broadwellx,core
 GenuineIntel-6-55-[56789ABCDEF],v1.16,cascadelakex,core
 GenuineIntel-6-9[6C],v1.03,elkhartlake,core
@@ -11,7 +11,7 @@ GenuineIntel-6-(3C|45|46),v32,haswell,co
 GenuineIntel-6-3F,v26,haswellx,core
 GenuineIntel-6-(7D|7E|A7),v1.15,icelake,core
 GenuineIntel-6-6[AC],v1.16,icelakex,core
-GenuineIntel-6-3A,v22,ivybridge,core
+GenuineIntel-6-3A,v23,ivybridge,core
 GenuineIntel-6-3E,v22,ivytown,core
 GenuineIntel-6-2D,v21,jaketown,core
 GenuineIntel-6-(57|85),v9,knightslanding,core
@@ -25,6 +25,6 @@ GenuineIntel-6-(4E|5E|8E|9E|A5|A6),v53,s
 GenuineIntel-6-55-[01234],v1.28,skylakex,core
 GenuineIntel-6-86,v1.20,snowridgex,core
 GenuineIntel-6-8[CD],v1.08,tigerlake,core
-GenuineIntel-6-2C,v2,westmereep-dp,core
+GenuineIntel-6-2C,v3,westmereep-dp,core
 GenuineIntel-6-25,v3,westmereep-sp,core
 GenuineIntel-6-2F,v3,westmereex,core
```

**Review by rpmclaug — APPROVED** [review]
As previously mentioned, basic/intermediate format checks passed.

**Pull request merged**
