### PR TITLE
Add E-core TMA3.6 perf json files

### PR DESCRIPTION
**Pull request by weilinwa**
Changes in the update:

1. Update to E-core TMA 3.6 
2. Add SRF and GRR metrics
3. Add cstate_module power metrics based on this kernel change: 
    https://git.kernel.org/pub/scm/linux/kernel/git/perf/perf-tools-next.git/commit/?id=3877d55a0db2688c2e4ab8a319614a0c81f8e2d2

### CODE REVIEW

**Comment by weilinwa** [comment]
Hi @edwarddavidbaker, could you please help me to add Ian, Kan, Ryan and Perry to be reviewers for this PR? Thanks a lot!

**Comment by edwarddavidbaker** [comment]
> Hi @edwarddavidbaker, could you please help me to add Ian, Kan, Ryan and Perry to be reviewers for this PR? Thanks a lot!

Done!

**Comment by rpmclaug** [comment]
I'm not familiar with these files, but the conversion of E-core TMA seems reasonable.

I am curious why some events are not surounded with cpu_atom@...@ while others are not. 
https://github.com/intel/perfmon/pull/194/files#diff-16336eaa0d15c1d2b7ab2061c4e7cdaa37939b8150f8fd29e492c51b8e1a68aaR407

**Comment by captain5050** [comment]
> I'm not familiar with these files, but the conversion of E-core TMA seems reasonable.
> 
> I am curious why some events are not surounded with cpu_atom@...@ while others are not. https://github.com/intel/perfmon/pull/194/files#diff-16336eaa0d15c1d2b7ab2061c4e7cdaa37939b8150f8fd29e492c51b8e1a68aaR407

Good catch, I don't think that is working as intended. The logic is supposed to replace all event names:
https://github.com/intel/perfmon/blob/main/scripts/create_perf_json.py#L1155

**Comment by weilinwa** [comment]
> > I'm not familiar with these files, but the conversion of E-core TMA seems reasonable.
> > I am curious why some events are not surounded with cpu_atom@...@ while others are not. https://github.com/intel/perfmon/pull/194/files#diff-16336eaa0d15c1d2b7ab2061c4e7cdaa37939b8150f8fd29e492c51b8e1a68aaR407
> 
> Good catch, I don't think that is working as intended. The logic is supposed to replace all event names: https://github.com/intel/perfmon/blob/main/scripts/create_perf_json.py#L1155

@captain5050 , the regular expression failed to substitute when the event is at the end of the line. I added another substitution for it and updated the JSON files. Please take a look.

**Review by 1perrytaylor — APPROVED** [review]

**Review by kliang2 — APPROVED** [review]
Looks good to me

**Pull request merged**
