### PR TITLE
Tma metrics v4.5

### PR DESCRIPTION
**Pull request by ayasini**

### CODE REVIEW

**Comment by edwarddavidbaker** [comment]
Thanks for creating the pull request Ahmad. Automated checks for `create_perf_json.py` are failing on missing event `UNC_ARB_TRK_OCCUPANCY.RD`. 
```
AssertionError: Expected UNC_ARB_TRK_OCCUPANCY.RD to be an event in "MEM_Read_Latency": "(UNC_ARB_TRK_OCCUPANCY.RD + UNC_ARB_DAT_OCCUPANCY.RD) / UNC_ARB_TRK_REQUESTS.RD" on ADL
```

Which of the following do you want to do?
1. Merge this pull request, then update event files.
2. Update event files so that there are no missing events, then merge this pull request.

**Comment by edwarddavidbaker** [comment]
+Ian so that he is also aware of metric changes. @captain5050

**Comment by captain5050** [comment]
Thanks Ed, I was aware of the missing events. I thought the event data was going to be updated before pushing TMA metrics 4.5. Would it be possible to also push the full excel spreadsheet version? The CSV files only contain the first sheet, and having all sheets with all levels is my preference.

**Comment by ayasini** [comment]
Ed,
These missing UNC_ARB_ events are known for the last few releases. (It is not specific for 4.5).

I believe Luis is working to publish these events for the relevant client models.

Ahmad

**Comment by edwarddavidbaker** [comment]
* Verified `create_perf_json.py` passes locally after rebasing this branch. 
* @captain5050 Double checking. You are requesting the `TMA_Metrics-full.xlsx` pair to `TMA_Metrics-full.csv`?

**Comment by captain5050** [comment]
> * @captain5050 Double checking. You are requesting the `TMA_Metrics-full.xlsx` pair to `TMA_Metrics-full.csv`?

Yeah, that would be great to have. Thanks!

**Comment by edwarddavidbaker** [comment]
@captain5050 I opened https://github.com/intel/perfmon/issues/52 to keep track of your feedback. Thanks Ian.

**Pull request merged**
