### PR TITLE
TMA 4.7 Update

### PR DESCRIPTION
**Pull request by calebbiggers**
Updated HSX, BDX, CLX, SKX, ICX, and SPR platforms with TMA 4.7

### CODE REVIEW

**Review by 1perrytaylor — APPROVED** [review]

**Review by captain5050 — CHANGES_REQUESTED** [review]
Hi, has the substitution of #smt_on in the perf metrics been broken? It looks like "1" is always substituted, e.g.

```
        "MetricExpr": "( ( IDQ.MITE_CYCLES_ANY - IDQ.MITE_CYCLES_OK ) / ( CPU_CLK_UNHALTED.DISTRIBUTED if ( 1 ) else ( CPU_CLK_UNHALTED.THREAD ) ) / 2 )",
        "MetricGroup": "DSBmiss;FetchBW;TopdownL3;tma_L3_group;tma_fetch_bandwidth_group",
        "MetricName": "tma_mite",
```

**Comment by captain5050** [comment]
Hi Caleb, would it be possible to squash thing change into the TMA 4.7 update?

**Comment by calebbiggers** [comment]
> Hi Caleb, would it be possible to squash thing change into the TMA 4.7 update?
@captain5050 As I merged some recent changes in-between the two commits, I cannot squash the changes into the original commit. I can close this PR and make a new one that only includes the fixed metrics. Is that preferred?

**Comment by edwarddavidbaker** [comment]
> @captain5050 As I merged some recent changes in-between the two commits, I cannot squash the changes into the original commit. I can close this PR and make a new one that only includes the fixed metrics. Is that preferred?

Your development branch will cleanly rebase on top of main. Try `git rebase -i origin/main` and select `s` for the second commit `8dfd9e7 Fix for removal of SMT_on constant`. Fixup the combined commit message as necessary.

**Comment by edwarddavidbaker** [comment]
@calebbiggers I spent a few minutes looking at the current failures.
```text
Creating event json for BDX in /home/runner/work/perfmon/perfmon/scripts/perf/broadwellx
    Mapfile(basepath).to_perf_json(outdir)
  File "/home/runner/work/perfmon/perfmon/scripts/create_perf_json.py", line 1842, in to_perf_json
    model.to_perf_json(modeldir)
  File "/home/runner/work/perfmon/perfmon/scripts/create_perf_json.py", line 1676, in to_perf_json
    csv_metrics = self.extract_tma_metrics(metric_csv, pmu_prefix, events)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/perfmon/perfmon/scripts/create_perf_json.py", line 1514, in extract_tma_metrics
    save_form(em['MetricName'], em['MetricGroup'], em['MetricExpr'],
  File "/home/runner/work/perfmon/perfmon/scripts/create_perf_json.py", line [120](https://github.com/intel/perfmon/actions/runs/7660092214/job/20876636275?pr=133#step:5:121)5, in save_form
    assert v in events or v.upper() in events or v in infoname or v in aux, \
AssertionError: Expected power to be an event in "tma_info_system_power": "( power@energy\-pkg@ * ( 61 ) + 15.6 * power@energy\-ram@ ) / ( ( ( duration_time * 1000 ) / 1000 ) * ( 1000000 ) )" on BDX
Error: Process completed with exit code 1.
```

I believe we want to skip `tma_info_system_power` using the existing `ignore` list. https://github.com/intel/perfmon/blob/09c155f72e1b8f14b09aea346a35467a03a7d62b/scripts/create_perf_json.py#L637-L642


A patch similar to the following should work.
```patch
@@ -1171,6 +1180,9 @@ class Model:
 
             def save_form(name, group, form, desc, locate, scale_unit, threshold,
                           issues):
+                if name in ignore:
+                    _verboseprint2(f'Dropping {self.shortname} metric {name}.')
+                    return
                 if self.shortname == 'BDW-DE':
                     if name in ['tma_false_sharing']:
                         # Uncore events missing for BDW-DE, so drop.
```

**Comment by captain5050** [comment]
I think we want to keep the metrics but need to update the skip here:
https://github.com/intel/perfmon/blob/09c155f72e1b8f14b09aea346a35467a03a7d62b/scripts/create_perf_json.py#L1193-L1201
to handle the power metrics case, like it is doing for cpu. The assert assumes the events for the metric are either in that list or are defined in the architecture's event json files.

**Pull request merged**
