### PR TITLE
Perf converter script updates for TMA4.8 and E-core 3.6

### PR DESCRIPTION
**Pull request by weilinwa**
This PR updates the perf converter script. Changes in this PR:

1. Changes for TMA4.8 release
2. Changes for E-core 3.6 release
3. Changes to fix the uncore events that use filter1

### CODE REVIEW

**Comment by weilinwa** [comment]
@edwarddavidbaker, here is the code changes. This update would break the create-perf-json check because it includes TMA4.8 changes.

**Review by captain5050 — APPROVED** [review]

**Review by captain5050 — APPROVED** [review]

**Review by captain5050 — APPROVED** [review]

**Review by captain5050 — APPROVED** [review]

**Comment by edwarddavidbaker** [comment]
> @edwarddavidbaker, here is the code changes. This update would break the create-perf-json check because it includes TMA4.8 changes.

Is this short term? It is good to have the script running as part of basic CI checks. At the very least it reminds me to implement a few updates for new platforms.

**Comment by weilinwa** [comment]
> > @edwarddavidbaker, here is the code changes. This update would break the create-perf-json check because it includes TMA4.8 changes.
> 
> Is this short term? It is good to have the script running as part of basic CI checks. At the very least it reminds me to implement a few updates for new platforms.

Hi Ed, sorry that I just see your comments. This code change was up-to-date that covers all the updates for p-core TMA4.8 and E-core TMA3.6. The check fail because the spreadsheet in this repo is out dated so that the script and the spreadsheet don't match with each other. In the other PR (#226) that changes this script to use JSON input on default, we should do have the version mis-match issue anymore. 

That PR (#226) is based on top of code from this PR. I think we could close this PR without merging and focus on the other PR only.

**Comment by edwarddavidbaker** [comment]
> That PR (#226) is based on top of code from this PR. I think we could close this PR without merging and focus on the other PR only.

@weilinwa That works for me. Thanks for the information.

**Pull request closed without merging**
