### PR TITLE
EMR, MTL, ADL: Release event updates

### PR DESCRIPTION
**Pull request by edwarddavidbaker**
## Platform updates
* EMR
    *  Add `PDISTCounter` core attribute.
    * Release uncore experimental events `UNC_CHA_TOR_INSERTS.IA_MISS_DRD_CXL_EXP_LOCAL`, `UNC_CHA_TOR_INSERTS.IA_MISS_RFO_CXL_EXP_LOCAL`, `UNC_CHA_TOR_OCCUPANCY.IA_MISS_DRD_CXL_EXP_LOCAL`, and `UNC_CHA_TOR_OCCUPANCY.IA_MISS_RFO_CXL_EXP_LOCAL`.
* MTL
   * Add `Precise` core attribute.
   * Release E-core event `BR_MISP_RETIRED.NEAR_TAKEN`.
   * Update P-core OCR counters and release `MEMORY_ACTIVITY.CYCLES_L1D_MISS`.
   * Release uncore fixed event `UNC_CLOCK.SOCKET`.
* ADL
   * Add `Precise` core attribute.
   * Release E-core event `BR_INST_RETIRED.NEAR_TAKEN`.
   *  Update P-core OCR counters.

## Readme updates
* Added `Precise` section to event attribute descriptions.
* Added notice to `PEBS` attribute description. For platforms starting with ICL and ICX, downstream users and tools will need to migrate from `PEBS` to `Precise` and existing attributes such as `CollectPEBSRecord`. Additional notes are tracked at https://github.com/intel/perfmon/issues/114.

### CODE REVIEW

**Comment by edwarddavidbaker** [comment]
* Event files were reviewed and approved internally.
* @lfrusa I revisited README.md since MTL and ADL include `Precise` in these files . To diff the changes manually, try opening each.
    1. https://github.com/intel/perfmon/blob/main/README.md#event-list-field-definitions
    2. https://github.com/edwarddavidbaker/perfmon/tree/sync-platforms#event-list-field-definitions

**Comment by lfrusa** [comment]
I noticed ADL and MTL got PRECISE and PDIST_COUNTER attributes correctly, while EMR only got PDIST_COUNTER but is missing PRECISE. We'll want to add that update to our next release!

**Review by lfrusa — APPROVED** [review]
Updated attributes and Readme look good. We'll just need to add PRECISE to EMR for next release.

**Comment by edwarddavidbaker** [comment]
Thanks for reviewing README changes Fernando.

**Pull request merged**
